version: '3.8'

services:
  portfolio:
    # build: .
    image: yourusername/portfolio-app:latest
    container_name: portfolio-app
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80