name: Deploy Portfolio to Docker Hub

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: himanshutoshniwal7570/portfolio-app:latest
    
    - name: Deployment Success
      run: |
        echo "✅ Portfolio successfully built and pushed to Docker Hub!"
        echo "🚀 Image: himanshutoshniwal7570/portfolio-app:latest"
        echo "📦 Pull command: docker pull himanshutoshniwal7570/portfolio-app:latest"